routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;







Route::resource('category', CategoryController::class)->only(
    [
        'index',
        'show',
    ]
);
Route::resource('product', ProductController::class)->only(
    [
        'show',
    ]
);

Route::resource('cart', CartController::class,)
    ->only(
        [
           'index',
        ]
    )->middleware('auth');

Route::group(['prefix'=>'cart','middleware'=>['auth']], function (){
    Route::get('/addProduct/{id}',[CartController::class,'addProduct'])->name('add_product_to_cart');
    Route::get('/destroyProduct/{id}',[CartController::class,'deleteProduct'])->name('delete_product_to_cart'); // Заменить на delete, нужно было установить ajax
});


Route::group(['prefix'=>'auth'], function (){
    Route::post('/login',[AuthController::class,'login'])->name('login');
    Route::get('/login',[AuthController::class,'loginShow']);
    Route::get('/logout',[AuthController::class,'logOut'])->name('logout');
});



Route::get('/',function (){
    return redirect()->route('category.index');
})->name('dashboard');

app/Models/Cart.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cart extends Model
{
    public $timestamps = false;

    protected $fillable = [
        'id',
        'user_id',
    ];

    public function items()
    {
        return $this->hasMany(CartProducts::class,'cart_id','id');
    }
}

app/Models/CartProducts.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CartProducts extends Model
{
    use HasFactory;

    protected $fillable = [
        'cart_id',
        'product_id',
        'count',
    ];

    public $timestamps = false;

    public function products()
    {
        return $this->hasOne(Product::class,'id','product_id');
    }
}

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    public $timestamps = false;

    protected $fillable = [
        'title',
        'parent_id',
    ];

    public function scopeRoot($query)
    {
        $query->whereNull('parent_id');
    }

    public function children()
    {
        return $this->hasMany($this,'parent_id','id');
    }

    public function products()
    {
        return $this->hasMany(Product::class,'category_id','id');
    }
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'description',
        'price',
        'category_id',
    ];


}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function cart()
    {
        return $this->hasOne(Cart::class,'user_id','id');
    }
}

app/Http/Controllers/AuthController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\LoginRequest;
use App\Services\AuthService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AuthController extends Controller
{

    private object $authService;

    public function __construct(AuthService $authService)
    {
        $this->authService = $authService;
    }

    public function login(LoginRequest $request)
    {
        $payload = $request->only(
            [
                'email',
                'password',
            ]
        );

        return $this->authService->login($payload);
    }

    public function loginShow()
    {
        return view('auth.login');
    }

    public function logOut(Request $request)
    {
        Auth::logout();

        $request->session()->invalidate();

        $request->session()->regenerateToken();

        return redirect('/');

    }
}

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CartAddProductRequest;
use App\Http\Requests\CartDeleteProductRequest;
use App\Http\Requests\CartStoreRequest;
use App\Services\CartService;
use Illuminate\Http\Request;

class CartController extends Controller
{

    private object $cartService;

    public function __construct(CartService $cartService)
    {
        $this->cartService = $cartService;
    }

    public function index(Request $request)
    {
        return $this->cartService->showCart();
    }

    public function store(CartStoreRequest $request)
    {

    }

    public function addProduct(CartAddProductRequest $request)
    {
        return $this->cartService->addProductToCart($request->product_id);
    }

    public function deleteProduct(CartDeleteProductRequest $request)
    {
        return $this->cartService->deleteProductToCart($request->product_id);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;


use App\Http\Requests\CategoryShowRequest;
use App\Services\CategoryService;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    private object $categoryService;

    public function __construct(CategoryService $categoryService)
    {
        $this->categoryService = $categoryService;
    }

    public function index(): object
    {
        return $this->categoryService->getAllRootCategories();
    }

    public function show(CategoryShowRequest $request)
    {
        return $this->categoryService->getCategoryWithChildAndProducts($request->id);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductShowRequest;
use App\Services\ProductService;
use Illuminate\Http\Request;

class ProductController extends Controller
{

    private object $productService;

    public function __construct(ProductService $productService)
    {
        $this->productService = $productService;
    }

    public function show(ProductShowRequest $request)
    {
        return $this->productService->getProductById($request->id);
    }
}

resources/views/cart/index.blade.php
<style>
    table, th, td {
        border: 1px solid;
    }

    table {
        width: 100%;
    }
</style>
<body>
@include('header')
<h2 style="text-align: center">Корзина | Сумма: {{$totalprice}} $</h2>

<div style="margin: auto; width: 50%">
    <table>
        <tr>
            <th>Название продукта</th>
            <th>Кол-во продукта в корзине</th>
            <th>Инструменты</th>
        </tr>
        @foreach($products as $product)
            <tr>
                <th><a href="{{route('product.show',$product->products()->first()->id)}}">{{$product->products()->first()->title}}</a></th>
                <th>{{$product->count}}</th>
                <th>
                    <a href="{{route('add_product_to_cart',$product->product_id)}}"><button>Добавить</button></a>
                    <a href="{{route('delete_product_to_cart',$product->product_id)}}"><button>Удалить</button></a>
                </th>
            </tr>
        @endforeach
    </table>
</div>
</body>

resources/views/categories/index.blade.php
<body>
@include('header')
<h2>Категории</h2>
@foreach($categories as $category)
    <div>
        <a href="{{route('category.show',$category->id)}}">{{$category->title}}</a>

        @foreach($category->children as $child)
            <div style="margin-left: 20px">
                <a href="{{route('category.show',$child->id)}}">{{$child->title}}</a>
            </div>
        @endforeach
    </div>
@endforeach
</body>

resources/views/categories/show.blade.php
<body>
@include('header')
<h2 style="text-align: center"><a href="{{url()->previous()}}">Назад</a> Категория {{$category->title}}</h2>
<div style="text-align: center">
<ul>
@foreach($category->products as $product)
        <li><a href="{{route('product.show',$product->id)}}">{{$product->title}}</a></li>
@endforeach
</ul>
</div>
</body>

resources/views/header.blade.php
@if(\Illuminate\Support\Facades\Auth::check())
    <h4>Hi, {{auth()->user()->name}}({{auth()->user()->email}}) <a href="{{route('logout')}}"/>Выйти</a></h4>
    <h4><a href="{{route('category.index')}}">Категории</a> <a href="{{route('cart.index')}}">Корзина</a></h4>
@else
    <div><a href="{{route('login')}}">Войти</a></div>
@endif

resources/views/products/show.blade.php
<body>
@include('header')
<div style="text-align: center">
    <h1>{{$product->title}}</h1>
    <h2>{{$product->description}}</h2>
    <h3>В наличие: {{$product->count}}</h3>
    <h3>Цена: {{$product->price}} $</h3>
    <a href="{{route('add_product_to_cart',$product->id)}}"><button>Добавить в корзину</button></a>
</div>
</body>